### ISSUE TITLE
[Question]  Discord webhook i need to create a whitelist that  the webhook reacts too (grabs)

### ISSUE THREAD

**Issue by wolflord212312** [ReinforceZwei/Minecraft-Console-Client#12]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

build 531

### Description of the Question

Im trying to get the webhook to only find the leaderboard.

### Solutions you've already considered

1. editing the whole script to make it only detect 1 chat
2. have someone add on to it to add a whitelist and black list 

### Minecraft Version

1.12.2

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

play.jailmc.com

**Comment by ReinforceZwei** [comment]
Hi, this is a forked repository of Minecraft Console Client. Please go to the main repository for any issues or questions.
